baseURL       = "https://1665plague.rrchnm.org/"
title         = "Gaming the Great Plague"
languageCode  = "en-us"
themesDir     = "../themes"
theme         = "rrchnm"

[params]
  siteName     = "Gaming the Great Plague"
  tagline      = "Can You Survive Living in London, 1665–1666?"
  primary       = "#008285"
  primaryDark   = "#006568"
  primaryDeep   = "#00484A"
  primarySoft   = "#E5F1F1"
  primaryBright = "#1AAFB2"
  contactEmail = "chnm@gmu.edu"

[[menus.main]]
  name   = "Home"
  url    = "/"
  weight = 1

[[menus.main]]
  name   = "Game"
  url    = "https://jmotis.github.io/GamingtheGreatPlague"
  weight = 2

[[menus.main]]
  name   = "Pedagogical Materials"
  url    = "/pedagogical-materials/"
  weight = 3

[[menus.main]]
  name   = "About"
  url    = "/about/"
  weight = 4
